spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    #    addresses: add.com
    #    username: username
    #    password: password
    #    virtual-host: hostname
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2
#        prefetch: 1

