spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

    #    addresses: add.com
    #    username: username
    #    password: password
    #    virtual-host: hostname
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
